version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Docker/app.Dockerfile
    ports:
      - "8000:8000"
    environment:
      ROCKET_ADDRESS: "0.0.0.0"

  db:
    build:
      context: .
      dockerfile: ./Docker/db.Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: notproduction
      POSTGRES_USER: dnguyen-blog
